USE Reliance
GO

select count(*) 
from CORRACT.BC_DETERMINATION

SELECT TOP 1000 * FROM CORRACT.BC_DETERMINATION where etq$created_date > '3/1/12'

SELECT
	sysobjects.schema,
    sysobjects.Name,
    , sysindexes.Rows
FROM
    sysobjects INNER JOIN sysindexes ON sysobjects.id = sysindexes.id
WHERE
    type = 'U'
    AND sysindexes.IndId < 2
ORDER BY
    sysobjects.schema, sysobjects.Name
    
    select * from sysobjects


ELECT COUNT(*) FROM CORRACT

SELECT DISTINCT FROM RELI


select * from corract.bc_routing_occurrence_sub
select * from corract.bc_attachment_1
select * from engine.user_settings
select * from engine.document_library
select * from corract.document_info
select * from lookups.bc_occurrence_codes
SELECT * FROM lookups.bc_complaint_cat
select * from lookups.[BC_COMPLAINT_OPTIONS]
select * from lookups.[BC_PACKAGING]
select * from LOOKUPS.BC_OCCURRENCE_CODES
select * from lookups.bc_test_equipment
select * from lookups.bc_disposition

select * from corract.ETQ$BC_DETERMINATION_FH where bc_determination_id = 63455
select * from lookups.etq$field
select * from lookups.comments
select * from engine.dialog_fields

select * from lookups.bc_outcome_disp
select * from engine.phase_routing_types
select * from lookups.yes_no_combobox


SELECT etq$reason FROM corract.bc_determination where etq$reason is not null
select * from engine.phase_routing_types
select bc_patient_sex, count(*) from corract.bc_determination group by bc_patient_sex
select tsl_billing_adj, count(*) from corract.bc_determination group by tsl_billing_adj
select [BC_SURG_LNAME], count(*) from corract.bc_determination group by [BC_SURG_LNAME]

select bc_code1, count(*) from corract.bc_determination group by bc_code1


select * 
from corract.bc_determination bcd
where bcd.bc_determination_id = bcd.etq$original_doc_id

--All open occurences
 SELECT BC_DETERMINATION.ETQ$NUMBER, 
		LOCATION_PROFILE.HIERARCHICAL_NAME, 
		USER_SETTINGS.DISPLAY_NAME, 
		PHASE_SETTINGS.PHASE_TYPE, 
		PHASE_SETTINGS.DISPLAY_NAME, 
		BC_DETERMINATION.ETQ$NUMBER_ONLY, 
		BC_DETERMINATION.ETQ$CREATED_DATE, 
		BC_DETERMINATION.ETQ$NUMBER
 FROM   ((((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
		LEFT OUTER JOIN RELIANCE.ENGINE.PHASE_SETTINGS PHASE_SETTINGS 
		ON BC_DETERMINATION.ETQ$CURRENT_PHASE=PHASE_SETTINGS.PHASE_ID) 
		LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_ASN ETQ_BC_DETERMINATION_ASN 
		ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_ASN.BC_DETERMINATION_ID) 
		LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_LOCS ETQ_BC_DETERMINATION_LOCS 
		ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_LOCS.BC_DETERMINATION_ID) 
		LEFT OUTER JOIN RELIANCE.ENGINE.USER_SETTINGS USER_SETTINGS 
		ON ETQ_BC_DETERMINATION_ASN.ETQ$ASSIGNED=USER_SETTINGS.USER_ID) 
		LEFT OUTER JOIN RELIANCE.DATACENTER.LOCATION_PROFILE LOCATION_PROFILE 
		ON ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID=LOCATION_PROFILE.LOCATION_PROFILE_ID
 --WHERE  PHASE_SETTINGS.PHASE_TYPE=0 
	--AND LOCATION_PROFILE.HIERARCHICAL_NAME= 'BCS'
 ORDER BY  BC_DETERMINATION.ETQ$NUMBER_ONLY
 
 --All Occurances Export
  SELECT BC_DETERMINATION.ETQ$NUMBER, 
  BC_DETERMINATION.BC_CODE1, 
  BC_DETERMINATION.BC_CODE2, 
  BC_DETERMINATION.BC_CODE3, 
  BC_DETERMINATION.BC_CODE4, 
  BC_DETERMINATION.BC_CODE5, 
  ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID, 
  BC_DETERMINATION.ETQ$CURRENT_PHASE, 
  BC_DETERMINATION.BC_DATE_OCCURRED, 
  BC_LOCATION.DESCRIPTION, 
  BC_PROC_STEP_SUB.BC_EMPLOYEE_INVOLVED, 
  BC_DETERMINATION.BC_WHAT_HAPPENED, 
  BC_DETERMINATION.BC_INVESTIGATION, 
  BC_DETERMINATION.BC_IMMED_ACTION, 
  BC_DETERMINATION.BC_CORRECTIVE_ACTION,
  
 FROM   ((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
	INNER JOIN RELIANCE.LOOKUPS.BC_LOCATION BC_LOCATION 
	ON BC_DETERMINATION.BC_LOCATION=BC_LOCATION.BC_LOCATION_ID) 
	LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_LOCS ETQ_BC_DETERMINATION_LOCS 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_LOCS.BC_DETERMINATION_ID) 
	LEFT OUTER JOIN RELIANCE.CORRACT.BC_PROC_STEP_SUB BC_PROC_STEP_SUB 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=BC_PROC_STEP_SUB.BC_DETERMINATION_ID
 WHERE  BC_DETERMINATION.ETQ$CURRENT_PHASE<>819 
 AND ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID=2 
 AND (BC_DETERMINATION.BC_DATE_OCCURRED>={ts '2013-01-01 00:00:00'} 
 AND BC_DETERMINATION.BC_DATE_OCCURRED<{ts '2013-04-10 00:00:00'})
 ORDER BY BC_DETERMINATION.BC_CODE2, BC_DETERMINATION.BC_CODE3, BC_DETERMINATION.BC_CODE4, BC_DETERMINATION.BC_CODE5





SELECT DISTINCT DISPLAY_NAME 
FROM RELIANCE.ENGINE.PHASE_SETTINGS PS
INNER JOIN CORRACT.BC_DETERMINATION D ON D.ETQ$CURRENT_PHASE = PS.PHASE_ID

-- All occurences for a data range
SELECT BC_DETERMINATION.ETQ$NUMBER, 
	BC_DETERMINATION.BC_CODE1, 
	BC_DETERMINATION.BC_CODE2, 
	BC_DETERMINATION.BC_CODE3, 
	BC_DETERMINATION.BC_CODE4, 
	BC_DETERMINATION.BC_CODE5, 
	ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID, 
	BC_DETERMINATION.ETQ$CURRENT_PHASE, 
	BC_DETERMINATION.BC_DATE_OCCURRED, 
	BC_LOCATION.DESCRIPTION, 
	BC_PROC_STEP_SUB.BC_EMPLOYEE_INVOLVED, 
	BC_DETERMINATION.BC_WHAT_HAPPENED, 
	BC_DETERMINATION.BC_INVESTIGATION, 
	BC_DETERMINATION.BC_IMMED_ACTION, 
	BC_DETERMINATION.BC_CORRECTIVE_ACTION
FROM   ((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
	INNER JOIN RELIANCE.LOOKUPS.BC_LOCATION BC_LOCATION 
	ON BC_DETERMINATION.BC_LOCATION=BC_LOCATION.BC_LOCATION_ID) 
	LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_LOCS ETQ_BC_DETERMINATION_LOCS 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_LOCS.BC_DETERMINATION_ID) 
	LEFT OUTER JOIN RELIANCE.CORRACT.BC_PROC_STEP_SUB BC_PROC_STEP_SUB 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=BC_PROC_STEP_SUB.BC_DETERMINATION_ID
WHERE  BC_DETERMINATION.ETQ$CURRENT_PHASE<>819
	 AND ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID=2 
	 AND (BC_DETERMINATION.BC_DATE_OCCURRED>={ts '2013-01-01 00:00:00'} 
	 AND BC_DETERMINATION.BC_DATE_OCCURRED<{ts '2013-04-05 00:00:00'})
ORDER BY BC_DETERMINATION.BC_CODE2, BC_DETERMINATION.BC_CODE3, BC_DETERMINATION.BC_CODE4, BC_DETERMINATION.BC_CODE5

--DVR Occurence by Site
SELECT BC_DETERMINATION.BC_DATE_DISCOVERED, 
	BC_LOCATION.DESCRIPTION, 
	ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID, 
	BC_DETERMINATION.ETQ$NUMBER, 
	BC_DETERMINATION.BC_DATE_OCCURRED, 
	BC_DETERMINATION.ETQ$CURRENT_PHASE, 
	BC_PROC_STEP_SUB.BC_EMPLOYEE_INVOLVED, 
	PHASE_SETTINGS.DISPLAY_NAME, 
	BC_DETERMINATION.BC_CODE1, 
	BC_DETERMINATION.BC_CODE2, 
	BC_DETERMINATION.BC_CODE3, 
	BC_DETERMINATION.BC_CODE4, 
	BC_DETERMINATION.BC_CODE5, 
	BC_DETERMINATION.BC_DETERMINATION_ID, 
	BC_DETERMINATION.BC_INVESTIGATION
FROM   (((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
LEFT OUTER JOIN RELIANCE.LOOKUPS.BC_LOCATION BC_LOCATION 
	ON BC_DETERMINATION.BC_LOCATION=BC_LOCATION.BC_LOCATION_ID) 
LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_LOCS ETQ_BC_DETERMINATION_LOCS 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_LOCS.BC_DETERMINATION_ID) 
LEFT OUTER JOIN RELIANCE.CORRACT.BC_PROC_STEP_SUB BC_PROC_STEP_SUB 
	ON BC_DETERMINATION.BC_DETERMINATION_ID=BC_PROC_STEP_SUB.BC_DETERMINATION_ID) 
LEFT OUTER JOIN RELIANCE.ENGINE.PHASE_SETTINGS PHASE_SETTINGS 
	ON BC_DETERMINATION.ETQ$CURRENT_PHASE=PHASE_SETTINGS.PHASE_ID
WHERE  (BC_DETERMINATION.BC_DATE_DISCOVERED>={ts '2012-06-21 00:00:00'} 
	AND BC_DETERMINATION.BC_DATE_DISCOVERED<{ts '2013-03-22 00:00:00'}) 
	AND BC_DETERMINATION.ETQ$CURRENT_PHASE<>819 
	--AND ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID=19
ORDER BY BC_DETERMINATION.ETQ$NUMBER, ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID

select  from lookups.BC_LOCATION

select BC_NBR_OF_UNITS, count(*)
from corract.bc_determination
group by BC_NBR_OF_UNITS

use reliance
go

select * from RELIANCE.DATACENTER.LOCATION_PROFILE

select bcd.bc_location, bcl.bc_location_id, bcl.description, lp.display_name
FROM corract.bc_determination bcd
LEFT OUTER JOIN RELIANCE.LOOKUPS.BC_LOCATION bcl
	ON bcd.BC_LOCATION = bcl.BC_LOCATION_ID
LEFT OUTER JOIN datacenter.location_profile lp
	ON bcd.bc_location = lp.location_profile_id

	
SELECT  bcd.bc_location
FROM corract.bc_determination bcd
EXCEPT
SELECT * FROM RELIANCE.LOOKUPS.BC_LOCATION bcl

--Process Steps
SELECT BC_PROCESS_STEP.DESCRIPTION, 
BC_DETERMINATION.ETQ$NUMBER, 
BC_PROCESS_STEP_1.DESCRIPTION
FROM   ((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
RIGHT OUTER JOIN RELIANCE.CORRACT.BC_PROC_STEP_SUB BC_PROC_STEP_SUB 
ON BC_DETERMINATION.BC_DETERMINATION_ID=BC_PROC_STEP_SUB.BC_DETERMINATION_ID) 
LEFT OUTER JOIN RELIANCE.LOOKUPS.BC_PROCESS_STEP BC_PROCESS_STEP 
ON BC_PROC_STEP_SUB.BC_PROC_STEP_OCCURD=BC_PROCESS_STEP.BC_PROCESS_STEP_ID) 
LEFT OUTER JOIN RELIANCE.LOOKUPS.BC_PROCESS_STEP BC_PROCESS_STEP_1 
ON BC_PROC_STEP_SUB.BC_PROC_STEP_CAUGHT=BC_PROCESS_STEP_1.BC_PROCESS_STEP_ID
WHERE  (BC_PROCESS_STEP.DESCRIPTION<>N'null' 
OR BC_PROCESS_STEP_1.DESCRIPTION<>N'null')

--ORFs by DIN
SELECT BC_DETERMINATION.BC_DATE_DISCOVERED, 
ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID, 
BC_DETERMINATION.BC_CODE1, 
BC_DETERMINATION.BC_CODE2, 
BC_DETERMINATION.BC_CODE3, 
BC_DETERMINATION.BC_CODE4, 
BC_DETERMINATION.BC_CODE5, 
BC_DETERMINATION.ETQ$NUMBER, 
BC_DETERMINATION.BC_DATE_OCCURRED, 
BC_DETERMINATION.ETQ$CURRENT_PHASE, 
PHASE_SETTINGS.DISPLAY_NAME, 
BC_DINS_SUB.BC_DIN_STR, 
BC_DINS_SUB.BC_DIN_END, 
BC_LOCATION.DESCRIPTION, 
BC_DETERMINATION.BC_WHAT_HAPPENED, 
BC_DETERMINATION.BC_IMMED_ACTION
FROM   (((RELIANCE.CORRACT.BC_DETERMINATION BC_DETERMINATION 
INNER JOIN RELIANCE.CORRACT.BC_DINS_SUB BC_DINS_SUB 
ON BC_DETERMINATION.BC_DETERMINATION_ID=BC_DINS_SUB.BC_DETERMINATION_ID) 
LEFT OUTER JOIN RELIANCE.LOOKUPS.BC_LOCATION BC_LOCATION 
ON BC_DETERMINATION.BC_LOCATION=BC_LOCATION.BC_LOCATION_ID) 
LEFT OUTER JOIN RELIANCE.CORRACT.ETQ$BC_DETERMINATION_LOCS ETQ_BC_DETERMINATION_LOCS 
ON BC_DETERMINATION.BC_DETERMINATION_ID=ETQ_BC_DETERMINATION_LOCS.BC_DETERMINATION_ID) 
LEFT OUTER JOIN RELIANCE.ENGINE.PHASE_SETTINGS PHASE_SETTINGS 
ON BC_DETERMINATION.ETQ$CURRENT_PHASE=PHASE_SETTINGS.PHASE_ID
WHERE  BC_DETERMINATION.ETQ$CURRENT_PHASE<>819 
AND ETQ_BC_DETERMINATION_LOCS.ETQ$LOCATIONS_ID=2 
AND BC_DINS_SUB.BC_DIN_STR= 'W141612013356'

SELECT BC_DIN_STR, COUNT(*) 
FROM RELIANCE.CORRACT.BC_DINS_SUB
GROUP BY BC_DIN_STR
ORDER BY COUNT(*) DESC

